name: Testing

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  phpunit:
    name: PHP tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Cache wp-env
        uses: actions/cache@v4
        with:
          path: |
            ~/wp-env
            .wp-env/
          key: ${{ runner.os }}-wp-env-${{ hashFiles('.wp-env.json', 'package-lock.json') }}-v3
          restore-keys: |
            ${{ runner.os }}-wp-env-
      - name: Install dependencies
        run: npm ci
      - name: Start wp-env
        run: npm start
      - name: Test
        run: npm run test:php
      - name: Check Plugin
        run: npm run plugin:check

  vitest:
    name: JavaScript tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Run JavaScript tests
        run: npm run test:js
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Check versions
        run: bin/check-versions.sh
      - name: Zip
        run: bin/zip.sh
